### PR TITLE
add more code sections

### PR DESCRIPTION
**Pull request by binarynoise**
people are crazy when choosing what to put their code into

I'll probably add support for the new GitHub code editor later

### CODE REVIEW

**Comment by binarynoise** [comment]
I just saw that (at least in Firefox) the following syntax works: `:not(pre, code)` and it matches everything that is neither code nor pre. If that is a generally working syntax, that could clean the code up a bit and make the apply-monospace-in-code-areas-part easier

**Comment by vednoc** [comment]
> If that is a generally working syntax, that could clean the code up a bit and make the apply-monospace-in-code-areas-part easier

It's been around for a while now: https://caniuse.com/css-not-sel-list. I  suppose it could be converted to something like so:

```stylus
x = ()

append(x, 'x')
append(x, 'y')
append(x, 'z')

icons = unquote(join(', ', x))

:not({ icons }) {
    color: red
}

{ icons } {
    color: blue
}
```
```css
:not(x,
y,
z) {
  color: #f00;
}
x,
y,
z {
  color: #00f;
}
```

**Comment by vednoc** [comment]
I updated the code example to have both cases we'll use. If you have another idea/approach, I'm all ears!

**Comment by binarynoise** [comment]
-> #17

**Pull request closed without merging**
